# Generated by Django 4.0 on 2021-12-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='is_front_seat',
        ),
    ]
