# Generated by Django 4.0 on 2021-12-17 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_seat_is_front_seat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('row', 'seat_number')},
        ),
        migrations.RemoveField(
            model_name='seat',
            name='section',
        ),
    ]
