# Generated by Django 4.0 on 2021-12-17 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_seat_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='seat',
            managers=[
            ],
        ),
    ]
