# Generated by Django 4.0 on 2021-12-19 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_seat_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='tickets.section', verbose_name='Section'),
        ),
    ]
