# Generated by Django 4.0 on 2021-12-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_customer_aisle_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
